###user registration
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "firstName":"Lakshmi",
    "lastName":"Manoghna",
    "email":"manoghna@gmail.com",
    "password":"user@12345",
    "profileImageUrl":"https://example.com/avatars/user.png"
}

### author registration
POST http://localhost:4000/author-api/users
Content-Type:application/json

{
 "firstName":"Jaya",
 "lastName":"Tripuramalla",
 "email":"jaya@gmail.com",
 "password":"jaya@1234",
 "profileImageUrl":"https://example.com/avatars/author.png"   
}

###user authenticator
GET http://localhost:4000/common-api/login
Content-Type: application/json

{
    "email":"manoghna@gmail.com",
    "password":"manu@123"
}

###author authentication
GET http://localhost:4000/common-api/login
Content-Type: application/json

{
    "email":"jaya@gmail.com",
    "password":"jaya@1234"
}

###create article
POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author":"69896ea695e517fc7766aa65",
    "title":"test4 article",
    "category":"programming",
    "content":"content of test4 article"
}

###get the articles of author
GET http://localhost:4000/author-api/articles/69896ea695e517fc7766aa65

###update article
PUT http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author":"69896ea695e517fc7766aa65",
    "articleId":"69898e707aed8345c13ee4ff",
    "title":"test article",
    "category":"fundamentals",
    "content":"content of test article"
}

###logout
GET http://localhost:4000/common-api/logout

###get all articles
GET http://localhost:4000/user-api/articles

###delete the article
DELETE http://localhost:4000/author-api/69896ea695e517fc7766aa65/articleId/69898e917aed8345c13ee502

###add comments
PUT http://localhost:4000/user-api/add/69896816c8ba474e028289ab/articleId/698aa7e6a4717408604fd68a


###test res
GET http://localhost:4000/test

###admin login
GET http://localhost:4000/common-api/login
Content-Type: application/json

{
    "email":"santoshi@gmail.com",
    "password":"santu@123"
}

###block the user
GET http://localhost:4000/admin-api/block/69896816c8ba474e028289ab

###unblock the user
GET http://localhost:4000/admin-api/unblock/69896816c8ba474e028289ab

###change the password
PUT http://localhost:4000/common-api/change-password
Content-Type: application/json

{
    "email":"manoghna@gmail.com",
    "password":"user@12345",
    "newPassword":"manu@123"
}
